### ISSUE TITLE
GetPlayerIdentifiers(source)

### ISSUE THREAD

**Issue by SkOODaT** [Project-Entity/pe-adminmenu#1]
i would suggest either using
`local PEidentifier = GetPlayerIdentifier(source, 1)`
or
`	for k, o in ipairs(PEidentifier) do
	    if string.match(o, "license:") then
		    PEidentifier = o
		    break
	    end
	end`
to specifically use license for admin, if a player has a steam id setup it will override to that
might even want to consider comparing your PE.isAdmin table with GetPlayerIdentifiers

you might not be aware either but theirs 
`GetPlayerIdentifiers`
and
`GetPlayerIdentifier` [without the (s)]

**Comment by XiosBombay** [comment]
If you continue this, open an issue again
