### ISSUE TITLE
Issues with not recognising admin

### ISSUE THREAD

**Issue by RLMx94** [Project-Entity/pe-adminmenu#3]
Forgive me as i'm relatively new to coding, so it's probably an issue with something i am doing.. but it is not giving me perms... i have tried adding license & steamhex to the PEAdmins & /admin shows me as superadmin/owner but it will still not allow me to access the menu.

Any help is appreciated.

**Comment by XiosBombay** [comment]
So the admin menu does not use superadmin or admin. It is supposed to use identifiers. Do you mind sharing what you have on the local PE_Admins = {}

My discord is Bombay#1383 for a faster response.

**Comment by RLMx94** [comment]
It shows only this, 

local PEAdmins = {
    '9018ab5f277bce230942deffbf0db6c1b48ff80b',
}

**Comment by XiosBombay** [comment]
Oh, If this is your license add this
local PEAdmins = {
'license:9018ab5f277bce230942deffbf0db6c1b48ff80b',
}

**Comment by RLMx94** [comment]
'🛡️ | You cannot see this'

Still getting this..

**Comment by XiosBombay** [comment]
Fixed. Issue with license.
