### ISSUE TITLE
TP to player and From Issue

### ISSUE THREAD

**Issue by ProjectOhana21** [Project-Entity/pe-adminmenu#5]
Hello unsure if im missing a step but it appears that tp to player and bring player appear to have some hang ups where it looks as if it wants to but doesn't tp... Just shuts off the menu. Wondering if there was something I was missing.

**Comment by XiosBombay** [comment]
Do you mind recording a video?

**Comment by ProjectOhana21** [comment]
Hello sure thing though I might add after reinstalling I am no longer having that issue but now I am unable to just tp players to me or go to them. The notification for admin menu pops up but nothing else happens

**Comment by XiosBombay** [comment]
@ProjectOhana21 Ok, no problem. Well, do you have a video for that issue?

**Comment by XiosBombay** [comment]
If you need further help, open this issue again
