### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kristianm1** [Project-Entity/pe-adminmenu#8]
Hello,

I have installed it and my steam id is in the file. when i try to delete chat, other players get "you dont have permission to do that" - same when i use "announce restart". 
I also get this error in the console: SCRIPT ERROR: @pe-adminmenu/server/admin_sv.lua:77: attempt to call a nil value (field 'showHelpNotification')

Any fix?

**Comment by XiosBombay** [comment]
The clear chat should be fixed. I don't know about the error. What esx version are you using?

**Comment by kristianm1** [comment]
Weird, it says that the chat is deleted, but its still there for me. 
ESX 1.1.0

**Comment by XiosBombay** [comment]
I'm not sure about 1.1.0 since this is meant to be used for ESX 1.2 due to the fact that es_admin2 was created for that version.

**Comment by kristianm1** [comment]
Oh ok, then i need to try something else:) Thanks!
